### ISSUE TITLE
Upgrade for Accelerate 1.4

### ISSUE THREAD

**Issue by statusfailed** [tmcdonell/accelerate-blas#5]
Currently, accelerate-blas doesn't work with accelerate 1.4. 

I am working on [making the necessary changes](https://github.com/statusfailed/accelerate-blas/tree/upgrade-accelerate-1.4), but I haven't yet got the `llvm-cpu` and `llvm-ptx` code to compile (I think my branch is usable without the FFI code, though)

I will post updates to this issue if I get things working!

**Comment by tmcdonell** [comment]
I finished off the last remaining pieces from your branch, this should work now. Thanks!

**Comment by statusfailed** [comment]
Ah, thanks very much!! I haven't had much time in the last couple weeks :)
